name: Sync Fork

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'
          fetch-depth: 0
          token: ${{ secrets.OPENWRT_WORKFLOW_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Merge upstream changes
        run: |
          git remote add upstream https://github.com/sbwml/r4s_build_script.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories --no-edit || exit 1

      - name: Push changes
        run: git push

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
